fix(monero-*): fix test building, some tests
What remains:
  $ cargo test -p monero-harness -p monero-rpc -p monero-sys -p monero-tests
  error: 7 targets failed:
      `-p monero-sys --test sign_message`
  thread 'test_sign_message' panicked at monero-sys/tests/sign_message.rs:79:5:
  assertion `left == right` failed: Signatures should be the same when using same key and address
    left: "SigV2TaTzgYm3ZKF3SfG6JFiVKQdwKDNTjGiyYLpZz8LcuwuxbJZndhyFg3M6jif3jk2f8kPE4TeQMh2EiAWXcktqt7vG"
   right: "SigV28HFN64UUAzq5STURuWR9UKTZ6s5vzEZ18NxGogswLfdrAGExwL39RupTh9aNLeZWRELKGJy99vq5KPhgNqBTWx2b"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

      `-p monero-sys --test simple`
  thread 'main' panicked at monero-sys/tests/simple.rs:64:10:
  called `Result::unwrap()` on an `Err` value: Failed to transfer funds after multiple attempts: Failed to ensure transaction has one txid and at least one tx key before publ
  ishing

  Caused by:
      Expected at least one tx key, got 0

  These all want docker:
      `-p monero-harness --test monerod`
      `-p monero-harness --test wallet`
      `-p monero-tests --test transaction_keys`
      `-p monero-tests --test transfers`
      `-p monero-tests --test transfers_wrong_key`